#!/usr/bin/env bash

if [ $1 = "install" ]
then
    cargo build
elif [ $1 = "build" ]
then
    cargo build
elif [ $1 = "test" ]
then
    cargo test -q --lib > testing_logs.txt
    cargo run -q -- test
    # echo $? --no-fail-fast
else
    cargo run -q -- $1
fi